name: 'Setup node modules'
description: 'Install node and npm dependencies and cache them'
inputs:
  node-version:
    description: 'The version of NodeJS'
    required: true
    default: '14'
  cached-paths:
    description: 'The directories to cache'
    required: true
    default: './node_modules'
  cache-key:
    description: 'The cache key'
    required: true
    default: ${{ hashFiles('./package-lock.json') }}
runs:
  using: "composite"
  steps: 
    - uses: actions/setup-node@v2-beta
      with:
        node-version: ${{ inputs.node-version }}
    - uses: actions/cache@v2
      with:
        path: ${{ inputs.cached-paths }}
        key: ${{ inputs.cache-key }}
    - id: node_modules_exists
      run: 'if [ -d "node_modules" ]; then echo "::set-output name=value::yes"; else echo "::set-output name=value::no"; fi'
    - if: steps.node_modules_exists.outputs.value == 'no'
      run: npm i
