name: Run
on:
  push:
    branches: [main]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run the action
        uses: webNeat/setup-node-modules-action@v1
        with:
          node-version: 14